version: "3.8"

services:
  vue-app:
    container_name: vue_frontend
    build:
      context: ./vueApp
      dockerfile: Dockerfile
    tty: true
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
    - ./vueApp:/usr/src/app
    - node_modules:/usr/src/app/openpachislot-console/node_modules
    command: sh -c "npm run serve"
    depends_on:
      - postgres
    networks:
      - webnet

  go-app:
    container_name: go_server
    build:
      context: ./goApp
      dockerfile: Dockerfile
    volumes:
      - ./goApp:/project
    working_dir: /project
    tty: true
    env_file:
      - .env
    depends_on:
      - postgres
    command: sh -c 'go mod tidy && air -c .air.toml'
    networks:
      - webnet

  postgres:
    container_name: postgres_db
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - vue-app
      - go-app
    networks:
      - webnet

volumes:
  postgres_data:
  node_modules:

networks:
  webnet: