version: "3.8"

services:
  vue-app:
    build:
      context: ./vueApp
      dockerfile: Dockerfile
    tty: true
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    volumes:
    - ./vueApp:/usr/src/app
    - node_modules:/usr/src/app/openpachislot-console/node_modules
    command: sh -c "npm run serve"
    ports:
    - "${VUE_PORT}:8080"
    
  go-app:
    container_name: go_server
    build:
      context: ./goApp
      dockerfile: Dockerfile
    volumes:
      - ./goApp:/project
    working_dir: /project
    tty: true
    ports:
      - "${GO_PORT}:8080"
    env_file:
      - .env
    depends_on:
      - postgres
    command: sh -c 'go mod tidy && air -c .air.toml'

  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
  node_modules:
