version: "3.8"

services:
  go:
    container_name: main_server
    volumes:
      - ./:/project/
    working_dir: /project
    tty: true
    build: "./"
    ports:
      - 8080:8080
    env_file:
      - .env
    command: sh -c 'go mod tidy && air -c .air.toml'  # airを使ってホットリロード

  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 5432:5432
