name: Build and deploy Docker containers to an Azure Web App

env:
  AZURE_WEBAPP_NAME: openpachislot  # set this to the name of your Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      # Build and push vue-app container
      - name: Build and push vue-app container image to registry
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./vueApp
          push: true
          tags: ghcr.io/${{ env.REPO }}/vue-app:${{ github.sha }}

      # Build and push go-app container
      - name: Build and push go-app container image to registry
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./goApp
          push: true
          tags: ghcr.io/${{ env.REPO }}/go-app:${{ github.sha }}

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build-and-push
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: |
            'ghcr.io/${{ env.REPO }}/vue-app:${{ github.sha }}'
            'ghcr.io/${{ env.REPO }}/go-app:${{ github.sha }}'
